---
- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - role: aws/ec2
  vars:
    ami_image: ami-2a69be4c # 2017-11-04設定
    key_name: aws_hamayu
    tag_name: "wayak_tes"
    instance_type: "t2.micro"
    device_name: "/dev/xvda"
    device_type: "gp2"
    volume_size: 30
    region: ap-northeast-1
    security_group:
      - hamada_ssh_allow
    vpc_subnet_id: subnet-ef7033b7
    assign_public_ip: yes
